### ISSUE TITLE
Peer to Peer Code review Nov. 2nd.

### ISSUE THREAD

**Issue by Meri-MG** [gracekabaghe/portfolio#23]
Great job, Grace, and thanks for presenting your code to us. We have several suggestions for you for further improvement:
- According to HTML best practices it is advised to divide your html code into header, main and footer sections. 
- According to the project requirements the pop-up window should show up on the button click only, kindly, try to fix that issue.

**Comment by gracekabaghe** [comment]
Thanks for bringing up these issues. 

- The popup window is now hidden from the display.
- HTML5 has been implemented.
